[build-system]
# Further build requirements - like numpy & cython - come from setup.py via
# the PEP 517 interface.
requires = [
    "setuptools",
    "wheel",
    "oldest-supported-numpy",
    "packaging",
    "Cython >=0.29.21",
]
build-backend = "setuptools.build_meta"
