[build-system]
requires = [
    "setuptools >=42.0",
    "wheel",
    #"oldest-supported-numpy",
    # We need a relatively new NumPy for Blosc2
    "numpy",
    "packaging",
    "py-cpuinfo",
    "Cython >=0.29.21",
    "blosc2 >=0.6.2"
]
build-backend = "setuptools.build_meta"
